
server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: master:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
        datasource:
          ds1:
            nacos:
              server-addr: master:8848
              dataId: ${spring.application.name}
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: flow

feign:
  sentinel:
    enabled: true

service-url:
  nacos-user-service: http://nacos-payment-provider


management:
  endpoints:
    web:
      exposure:
        include: '*'

