server:
  port: 3344

spring:
  application:
    name: cloud-config3344-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tangandkai/springcloud-config.git #git git@github.com:tangandkai/springcloud-config.git  http://localhost:3344/main/config-dev.yml
          #搜索目录 http://localhost:3344/config/dev/main
          search-paths:
            - springcloud-config
      #读取分支
      label: main

eureka:
  client:
    #false表示不在注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: config-server
    prefer-ip-address: true