server:
  port: 8105

spring:
  application:
    name: cloud-consumer-feign-service-hystrix

eureka:
  client:
    #false表示不在注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 5000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 5000
  hystrix:
    enabled: true
