
server:
  port: 9005

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: master:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'