server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://master:3306/spring?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: Twk199475@ok
    driver-class-name: com.mysql.jdbc.Driver