server:
  port: 9527

spring:
  application:
    name: cloud-gateway9527-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://master:3306/spring?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: Twk199475@ok
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址,lb表示负载均衡
          predicates:
            - Path=/payment/discovery/**         # 断言，路径相匹配的进行路由
            - After=2021-02-23T15:51:37.485+08:00[Asia/Shanghai] #该时间之后才生效   curl http://localhost:9527/payment/discovery
            - Cookie=username,zzyy  #curl http://localhost:9527/payment/discovery --cookie "username=zzyy"
            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/discovery --cookie "username=zzyy" -H "X-Request-Id:1234"

eureka:
  client:
    #false表示不在注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true