server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://master:3306/spring?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: Twk199475@ok
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.tang.interfaces.bean

eureka:
  client:
    #false表示不在注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8002
    prefer-ip-address: true